import importlib

from app.models.admin import (
    clear_login_attempt_state,
    delete_homepage_hero_slide,
    get_default_hero_slides,
    get_default_page_content,
    get_homepage_filters,
    get_homepage_hero,
    get_homepage_hero_slides,
    get_homepage_trust_badges,
    get_login_attempt_state,
    get_page_content,
    get_site_setting,
    init_admin_db,
    save_homepage_filters,
    save_homepage_hero,
    save_homepage_hero_slide,
    save_homepage_trust_badge,
    save_login_attempt_state,
    set_site_setting,
    update_page_content,
    verify_admin_login,
)
from app.models.catalog import (
    DB_PATH,
    coerce_image_urls,
    delete_product,
    delete_uploaded_product_image,
    delete_uploaded_product_images,
    get_all_product_ids,
    get_all_products,
    get_product,
    get_products_by_ids,
    get_reviews_for_product,
    get_or_create_category,
    parse_price_value,
    save_image_file_for_hero,
    save_image_file_for_product,
    save_product,
    save_product_review,
    search_products,
)
from app.models.order import (
    build_admin_redirect,
    get_all_offers,
    get_all_orders,
    get_cart_snapshot,
    get_offer_by_code,
    initialize_cart,
    is_admin,
    is_ajax_request,
    parse_discount_percent,
    save_order,
    send_admin_success,
)
from app.models.shared import (
    CompatConnection,
    DB_PATH,
    DB_TYPE,
    ORDERS_DB_PATH,
    PRODUCT_DB_PATH,
    _slugify,
    get_connection,
)

admin_models = importlib.import_module('app.models.admin')
catalog_models = importlib.import_module('app.models.catalog')
order_models = importlib.import_module('app.models.order')
shared_models = importlib.import_module('app.models.shared')

__all__ = [
    'DB_TYPE',
    'DB_PATH',
    'PRODUCT_DB_PATH',
    'ORDERS_DB_PATH',
    'CompatConnection',
    '_slugify',
    'get_connection',
    'admin_models',
    'catalog_models',
    'order_models',
    'shared_models',
    'init_admin_db',
    'verify_admin_login',
    'get_login_attempt_state',
    'save_login_attempt_state',
    'clear_login_attempt_state',
    'get_default_hero_slides',
    'get_homepage_hero',
    'get_homepage_hero_slides',
    'save_homepage_hero_slide',
    'delete_homepage_hero_slide',
    'get_homepage_trust_badges',
    'save_homepage_trust_badge',
    'save_homepage_hero',
    'get_homepage_filters',
    'save_homepage_filters',
    'get_site_setting',
    'set_site_setting',
    'get_default_page_content',
    'get_page_content',
    'update_page_content',
    'DB_PATH',
    'coerce_image_urls',
    'delete_product',
    'delete_uploaded_product_image',
    'delete_uploaded_product_images',
    'get_all_product_ids',
    'get_all_products',
    'get_product',
    'get_products_by_ids',
    'get_reviews_for_product',
    'get_or_create_category',
    'parse_price_value',
    'save_image_file_for_product',
    'save_image_file_for_hero',
    'save_product',
    'save_product_review',
    'search_products',
    'build_admin_redirect',
    'get_all_offers',
    'get_all_orders',
    'get_cart_snapshot',
    'get_offer_by_code',
    'initialize_cart',
    'is_admin',
    'is_ajax_request',
    'parse_discount_percent',
    'save_order',
    'send_admin_success',
]

